server.port=8081
spring.datasource.url=jdbc:h2:file:./data/locationdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
weather.service.url=http://localhost:8082/weather
